find_package(Threads REQUIRED)
add_executable(snapshot_tests snapshot_tests.cpp)
target_link_libraries(snapshot_tests PRIVATE read_mostly::map Threads::Threads)
read_mostly_warnings(snapshot_tests)
add_test(NAME snapshot_tests COMMAND snapshot_tests)
set_tests_properties(snapshot_tests PROPERTIES TIMEOUT 30)
add_executable(map_tests map_tests.cpp)
target_link_libraries(map_tests PRIVATE read_mostly::map)
read_mostly_warnings(map_tests)
add_test(NAME map_tests COMMAND map_tests)
set_tests_properties(map_tests PROPERTIES TIMEOUT 60)
foreach(test_name allocation_failure_tests correctness_tests operational_tests)
    add_executable(${test_name} ${test_name}.cpp)
    target_link_libraries(${test_name} PRIVATE read_mostly::map)
    target_include_directories(${test_name} PRIVATE ${PROJECT_SOURCE_DIR}/src)
    read_mostly_warnings(${test_name})
    add_test(NAME ${test_name} COMMAND ${test_name})
    set_tests_properties(${test_name} PROPERTIES TIMEOUT 60)
endforeach()
